# Generated by Django 4.1.7 on 2023-03-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_time',
        ),
    ]
