# Generated by Django 4.1.7 on 2023-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_contact_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('drone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drone_slot_id', models.IntegerField(max_length=10)),
                ('location_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
