# Generated by Django 4.1.7 on 2023-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_slot_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drone',
            name='location_id',
            field=models.IntegerField(),
        ),
    ]
